### ISSUE TITLE
Please make requirement.txt and update the code 

### ISSUE THREAD

**Issue by WSrujan** [DivyaKumarBaid/Youtube_promotion_on_twitter#2]

**Comment by DivyaKumarBaid** [comment]
I had all the dependencies right there under the installation heading, but since you have asked for a separate file, I have included the requirement.txt. 
for the second point, I can't make out the meaning of updating the code I am busy right now learning react so if you have any solution for that please make a PR .

Thanks a lot for checking out the repo.

**Comment by WSrujan** [comment]
![image](https://user-images.githubusercontent.com/49693115/124004967-2a4fff00-d9f6-11eb-8b4b-8229067b17ec.png)
i am getting errors

**Comment by DivyaKumarBaid** [comment]
Yup, I saw it right now I guess the API working of youtube has changed. I am looking into it right now. It will be fixed as soon as possible. Thanks for updating this error to me.

**Comment by DivyaKumarBaid** [comment]
I have updated the code. I rectified the mistake of mine passing the whole list while requesting through API whereas now I am just passing the string. Now just have a look at the code and try to run it and if it runs ping me here I will close the issue. Thanks again for notifying me of the error.

**Comment by WSrujan** [comment]
Error again

**Comment by DivyaKumarBaid** [comment]
Send me error statement or the ss
